CREATE TABLE users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL

    --CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';
);

CREATE TABLE pets(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    breed VARCHAR(255),
    gender VARCHAR(255),
    spayed VARCHAR(255),
    description TEXT
);

CREATE TABLE applications(
    id INT PRIMARY KEY AUTO_INCREMENT,
    pet_id INT,
    applicant1_first_name VARCHAR(50) NOT NULL,
    applicant1_last_name VARCHAR(50) NOT NULL,
    applicant1_dob DATE NOT NULL,
    applicant2_first_name VARCHAR(50),
    applicant2_last_name VARCHAR(50),
    applicant2_dob DATE NOT NULL,
    address VARCHAR(255) NOT NULL,
    apartment_number VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    zipcode VARCHAR(255) NOT NULL,
    home_phone VARCHAR(20),
    cell_phone VARCHAR(20),
    email_address VARCHAR(100),
    house_ownership VARCHAR(10),
    residency_duration INT,
    plan_to_move_in_the_near_future BOOLEAN,
    landlord_condo_board_name VARCHAR(255),
    landlord_condo_board_phone_number VARCHAR(20),
    referral_source VARCHAR(255),
    household_adults_count INT,
    household_adults_relationships TEXT,
    household_adults_adoption_agreed BOOLEAN,
    household_children_count INT,
    household_children_ages VARCHAR(255),
    household_children_had_pets BOOLEAN,
    household_expect_current_situation_to_change BOOLEAN,
    household_allergic_to_pets BOOLEAN,
    household_allergic_to_pets_list TEXT,
    employment_employer VARCHAR(255),
    employment_position_held VARCHAR(255),
    employment_employer_address VARCHAR(255),
    employment_employer_city VARCHAR(255),
    employment_employer_state VARCHAR(255),
    employment_employer_zipcode VARCHAR(255),
    employment_duration VARCHAR(255),
    employment_employer_phone VARCHAR(20),
    pet_has_pets BOOLEAN,
    pet_pet1_name VARCHAR(255),
    pet_pet1_breed VARCHAR(255),
    pet_pet1_age INT,
    pet_pet1_gender ENUM('M', 'F'),
    pet_pet1_spayed BOOLEAN,
    pet_pet1_where_are_they TEXT,
    pet_pet2_name VARCHAR(255),
    pet_pet2_breed VARCHAR(255),
    pet_pet2_age INT,
    pet_pet2_gender ENUM('M', 'F'),
    pet_pet2_spayed BOOLEAN,
    pet_pet2_where_are_they TEXT,
    pet_pet3_name VARCHAR(355),
    pet_pet3_breed VARCHAR(355),
    pet_pet3_age INT,
    pet_pet3_gender ENUM('M', 'F'),
    pet_pet3_spayed BOOLEAN,
    pet_pet3_where_are_they TEXT,
    pet_have_you_ever_given_or_relinquished BOOLEAN,
    pet_given_circumstances TEXT,

    veterinarian_name VARCHAR(50),
    veterinarian_phone VARCHAR(20),
    veterinarian_last_visit TEXT,

    new_pet_how_long_have_you_been_looking VARCHAR(255),
    new_pet_what_will_you_feed VARCHAR(255),
    new_pet_how_often_will_you_feed VARCHAR(255),
    new_pet_time_adjust VARCHAR(255),
    new_pet_emergency_care_bill BOOLEAN,
    new_pet_maintenance_yearly_budget VARCHAR(50),
    new_pet_responsible_home_committed BOOLEAN,
    new_pet_plan_if_move VARCHAR(255),
    new_pet_where_will_it_be_kept_during_day_night VARCHAR(255),
    new_pet_primary_care_giver VARCHAR(50),
    new_pet_primary_care_giver_alternative VARCHAR(50),
    new_pet_emergency_care_giver VARCHAR(50),
    new_pet_times_outside_per_day INT,
    new_pet_house_train_plan TEXT,
    new_pet_fenced_in_yard BOOLEAN,
    new_pet_fenced_size_type TEXT,
    new_pet_hours_left_alone_per_day INT,
    new_pet_digging TEXT,
    new_pet_barking TEXT,
    new_pet_chewing TEXT,
    new_pet_separation_anxiety TEXT,
    new_pet_aggression TEXT,

    references_1 VARCHAR(50),
    references_1_relationship VARCHAR(50),
    references_1_phone VARCHAR(20),
    references_2 VARCHAR(50),
    references_2_relationship VARCHAR(50),
    references_2_phone VARCHAR(20),
    references_3 VARCHAR(50),
    references_3_relationship VARCHAR(50),
    references_3_phone VARCHAR(20),

    applicant VARCHAR(50),
    --applicant_date,
    --applicant_signature,
    co_applicant VARCHAR(50),
    --co_applicant_date,
    --co_applicant_signature,

    status ENUM('Pending', 'Approved', 'Denied') NOT NULL DEFAULT 'Pending',
    FOREIGN KEY (pet_id) REFERENCES pets(id)
);

--CREATE TABLE user(
--    user_id INT PRIMARY KEY,
--    username VARCHAR(255) NOT NULL,
--    password VARCHAR(40),

    --CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';

--);